# List comprehension

List comprehensions are a concise way to create a new list based on an existing list.

In [1]:
r = []
for i in range(5):
    r.append(i+1)
#     print(i)
#     print(5)
print(r)

[1, 2, 3, 4, 5]


In [2]:
[ i for i in range(5)]

[0, 1, 2, 3, 4]

In [3]:
[ i for i in range(10) if i>3]

[4, 5, 6, 7, 8, 9]

In [6]:
[i if i>=3 else (i*i*(i+1)) for i in range(5)]

[0, 2, 12, 3, 4]

## Numpy Array

In [12]:
import numpy as np
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [19]:
a.reshape(3,3).shape

(3, 3)

In [18]:
b = a.reshape(3,3)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
c = np.arange(0,10)
d = c.reshape(2,5)
e = c.reshape(5,2)
print(d)
print(e)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
