In [14]:
import numpy as np

In [15]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
int32
1


In [16]:
#Upcasting  : Upcasting in NumPy is the process of converting a data type to a larger data type. 
np.array([1,2,3.0])

array([1., 2., 3.])

In [17]:
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [18]:
np.array([1,2],ndmin=3)

array([[[1, 2]]])

## arange(start, stop, step) 
Return evenly spaced values within a given interval.

In [19]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## Linspace :
Return evenly spaced numbers over a specified interval.

In [20]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [31]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.random.random_sample((1,10))+5

array([[5.23193291, 5.07230901, 5.24180083, 5.44702806, 5.5163193 ,
        5.66685065, 5.84999343, 5.27623576, 5.55611823, 5.50348953]])

In [32]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
np.sum(a)

300

In [34]:
a.shape

(5, 5)

In [35]:
#Collapse on Row : Destroying the rows
np.sum(a,axis=0)

array([50, 55, 60, 65, 70])

In [36]:
np.sum(a,axis=0).shape

(5,)

In [37]:
#Collapse on Column : Destroying the columns
np.sum(a,axis=1)

array([ 10,  35,  60,  85, 110])

In [38]:
np.sum(a,axis=1).shape

(5,)

In [45]:
b = np.arange(8).reshape(4,2)
print(b)
print("Shape",b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Shape (4, 2)


In [42]:
#Collapse of rows
np.sum(b,axis=0)

array([12, 16])

In [43]:
b.shape

(4, 2)

In [47]:
#Collapse of columns
np.sum(a,axis=1)

array([ 10,  35,  60,  85, 110])

In [50]:
c = np.arange(30).reshape(2,5,3)
print(c)
print("Shape:",c.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
Shape: (2, 5, 3)


In [52]:
np.sum(c,axis=(0,2))

array([ 51,  69,  87, 105, 123])

In [56]:
d = np.sum(c,axis=1)
print(d)
print(d.shape)

[[ 30  35  40]
 [105 110 115]]
(2, 3)


In [58]:
np.sum(d,axis=1)

array([105, 330])