In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
int32
1


In [3]:
#Upcasting  : Upcasting in NumPy is the process of converting a data type to a larger data type. 
np.array([1,2,3.0])

array([1., 2., 3.])

In [4]:
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [5]:
np.array([1,2],ndmin=3)

array([[[1, 2]]])

## arange(start, stop, step) 
Return evenly spaced values within a given interval.

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## Linspace :
Return evenly spaced numbers over a specified interval.

In [7]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.random.random_sample((1,10))+5

array([[5.99595063, 5.17264266, 5.80105067, 5.07144243, 5.46979717,
        5.19678861, 5.15521779, 5.87717341, 5.13301555, 5.0004337 ]])

In [10]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [11]:
np.sum(a)

300

In [12]:
a.shape

(5, 5)

In [13]:
#Collapse on Row : Destroying the rows
np.sum(a,axis=0)

array([50, 55, 60, 65, 70])

In [14]:
np.sum(a,axis=0).shape

(5,)

In [15]:
#Collapse on Column : Destroying the columns
np.sum(a,axis=1)

array([ 10,  35,  60,  85, 110])

In [16]:
np.sum(a,axis=1).shape

(5,)

In [17]:
b = np.arange(8).reshape(4,2)
print(b)
print("Shape",b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Shape (4, 2)


In [18]:
#Collapse of rows
np.sum(b,axis=0)

array([12, 16])

In [19]:
b.shape

(4, 2)

In [20]:
#Collapse of columns
np.sum(a,axis=1)

array([ 10,  35,  60,  85, 110])

In [21]:
c = np.arange(30).reshape(2,5,3)
print(c)
print("Shape:",c.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
Shape: (2, 5, 3)


In [22]:
np.sum(c,axis=(0,2))

array([ 51,  69,  87, 105, 123])

In [23]:
d = np.sum(c,axis=1)
print(d)
print(d.shape)

[[ 30  35  40]
 [105 110 115]]
(2, 3)


In [24]:
np.sum(d,axis=1)

array([105, 330])

In [27]:
a = np.arange(0,10).reshape(2,5)
b = np.arange(11,21).reshape(2,5)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


In [28]:
np.concatenate((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
np.concatenate((a,b)).shape

(4, 5)

In [30]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [31]:
np.concatenate((a,b),axis=1).shape

(2, 10)

In [33]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [34]:
np.hstack((a,b)).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4, 11, 12, 13],
       [14, 15,  5,  6],
       [ 7,  8,  9, 16],
       [17, 18, 19, 20]])