In [1]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
int32
1


In [4]:
#Upcasting  : Upcasting in NumPy is the process of converting a data type to a larger data type. 
np.array([1,2,3.0])

array([1., 2., 3.])

In [6]:
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [7]:
np.array([1,2],ndmin=3)

array([[[1, 2]]])

## arange(start, stop, step) 
Return evenly spaced values within a given interval.

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## Linspace :
Return evenly spaced numbers over a specified interval.

In [13]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])