In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(arr.ndim)

[1 2 3 4 5]
int32
1


In [5]:
#Upcasting  : Upcasting in NumPy is the process of converting a data type to a larger data type. 
np.array([1,2,3.0])

array([1., 2., 3.])

In [6]:
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [7]:
np.array([1,2],ndmin=3)

array([[[1, 2]]])

## arange(start, stop, step) 
Return evenly spaced values within a given interval.

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## Linspace :
Return evenly spaced numbers over a specified interval.

In [9]:
np.linspace(1,10,9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.random.random_sample((1,10))+5

array([[5.26286698, 5.65973391, 5.16112982, 5.22613831, 5.27304467,
        5.73885955, 5.80089815, 5.98652708, 5.26766037, 5.22724015]])

In [12]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
np.sum(a)

300

In [14]:
a.shape

(5, 5)

In [15]:
#Collapse on Row : Destroying the rows
np.sum(a,axis=0)

array([50, 55, 60, 65, 70])

In [16]:
np.sum(a,axis=0).shape

(5,)

In [17]:
#Collapse on Column : Destroying the columns
np.sum(a,axis=1)

array([ 10,  35,  60,  85, 110])

In [18]:
np.sum(a,axis=1).shape

(5,)

In [19]:
b = np.arange(8).reshape(4,2)
print(b)
print("Shape",b.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
Shape (4, 2)


In [20]:
#Collapse of rows
np.sum(b,axis=0)

array([12, 16])

In [21]:
b.shape

(4, 2)

In [22]:
#Collapse of columns
np.sum(a,axis=1)

array([ 10,  35,  60,  85, 110])

In [23]:
c = np.arange(30).reshape(2,5,3)
print(c)
print("Shape:",c.shape)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
Shape: (2, 5, 3)


In [24]:
np.sum(c,axis=(0,2))

array([ 51,  69,  87, 105, 123])

In [25]:
d = np.sum(c,axis=1)
print(d)
print(d.shape)

[[ 30  35  40]
 [105 110 115]]
(2, 3)


In [26]:
np.sum(d,axis=1)

array([105, 330])

In [27]:
a = np.arange(0,10).reshape(2,5)
b = np.arange(11,21).reshape(2,5)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[11 12 13 14 15]
 [16 17 18 19 20]]


In [28]:
np.concatenate((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [29]:
np.concatenate((a,b)).shape

(4, 5)

In [30]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [31]:
np.concatenate((a,b),axis=1).shape

(2, 10)

In [32]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15],
       [ 5,  6,  7,  8,  9, 16, 17, 18, 19, 20]])

In [33]:
np.hstack((a,b)).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4, 11, 12, 13],
       [14, 15,  5,  6],
       [ 7,  8,  9, 16],
       [17, 18, 19, 20]])

##  List Comprehensions



In [45]:
lst = []
x = range(0,12,4)
for n in x:
    lst.append(n)
print(lst)

[0, 4, 8]


In [41]:
x = range(0,8,2)
for n in x:
  print(n)

0
2
4
6


In [46]:
lst = [1,2,3,4,5,6]
lst2 = []
for i in lst:
    lst2.append(i**2)
    
print(lst2)

[1, 4, 9, 16, 25, 36]


In [50]:
nums = [1,2,3,4,5,6]
square_numbers = [i**2 for i in nums]
print(square_numbers)

[1, 4, 9, 16, 25, 36]


In [53]:
## Filtering even number from a list

nums = []
for x in range(1,10):
    nums.append(x)
    
print(nums)

even_numbers = [n for n in nums if n%2 == 0]
print(even_numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 4, 6, 8]


In [55]:
nums = [ n for n in range(1,12)]
print(nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [56]:
##Flatnig a list of lists: 2 for loops

lists = [[1,2,3],[4,5,6],[7,8,9]]
flattend_list = [item for sublist in lists for item in sublist]
flattend_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [58]:
##Genrating a list of the first letters of words in a list:


words = ["Apple","Grapes","Kiwi","Banana","Guava"]
letters = [letter[0] for letter in words]
print(letters)


['A', 'G', 'K', 'B', 'G']


In [59]:
## Generating a list of sqare of even numbers 

numbers = [n**2 for n in range(1,11) if n%2==0]
numbers

[4, 16, 36, 64, 100]

In [60]:
##Converting a list of strings into list of integers 

strings = ["1","2","3","4","5"]
[int(s) for s in strings ]

[1, 2, 3, 4, 5]

In [62]:
## Generating the list of fibonchi sequence using a list comprehension

fibs = [0,1,2,3,5,8,13,21,34,55,89]
[fibs[i-1]+fibs[i-2] for i in range(2,len(fibs))]

[1, 3, 5, 8, 13, 21, 34, 55, 89]

In [67]:
## Gerating the list of all the divisors of a number:

number = 236
[i for i in range(1,number+1) if number%i==0]


[1, 2, 4, 59, 118, 236]